language: objective-c
before_install:
- wget http://dl.google.com/android/android-sdk_r24.4.1-macosx.zip
- unzip android-sdk_r24.4.1-macosx.zip
- export ANDROID_HOME=$PWD/android-sdk-macosx
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
- echo yes | android update sdk --filter android-23 --no-ui --force > /dev/null
- echo yes | android update sdk --filter android-24 --no-ui --force > /dev/null
- echo yes | android update sdk --filter android-25 --no-ui --force > /dev/null
- echo yes | android update sdk --filter build-tools-23.0.3 --all --no-ui --force > /dev/null
- echo yes | android update sdk --filter sysimg-23 --no-ui --force > /dev/null
- echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
- echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null

install:
- npm install -g cordova

script:
- cordova create hello com.example.hello HelloWorld
- cd hello
- cordova platform add ios
- cordova platform add android
- cordova plugin add https://github.com/testfairy/testfairy-cordova-plugin
- cordova build ios
- cordova build android
- cd ..

deploy:
  provider: npm
  email: support@testfairy.com
  api_key:
    secure: cAkxfGKlJCiDmoz/J7YyYwATNVvJDctygbiUJZi0gqAQnM96u61jkPt9cntoBFG+rlxQGdFNjYnt4sEwjDkgOk17mRsqZocjQFsIorKjT2TIB1nJmCt2CFyJCamyxjBRxCrj0+MmlwYmHVnFPZ2vWOQ/HusBVQ5/ZSPO6wDBuXw=
  on:
    tags: true
    repo: testfairy/testfairy-cordova-plugin
